### ISSUE TITLE
Can't read wide results

### ISSUE THREAD

**Issue by spemberton** [gchaincl/httplab#38]
The data sent with a POST was a single very long line.

I could only read the beginning of the line; there seems to be no way to wrap the output received.

**Comment by gchaincl** [comment]
This has been discussed before in #26, I honestly haven't been able to come up with a nice solution.
There's currently 2 workarounds, 1) use <kbd>Ctrl+t</kbd> to toggle the responses column, so that you will have more space on the request inspection window, and 2) you can try to save the request into a file using <kbd>Ctrl + f</kbd>

**Comment by spemberton** [comment]
My response body is *very* long. ctrl-t doesn't even start to address the problem :-)
As you will see, save to file doesn't work for me.
But can't you use a ctrl-key to toggle wrapping on and off, so that long lines at least become visible?

Very nice program, by the way. Exactly what I needed :-)

**Comment by gchaincl** [comment]
Toggle line wrap is something I definitely need to start working on. About saving #37 you need to save the request, not the response.
